#!/usr/bin/env python3

import sys, time

from PyQt5 import QtCore, QtWidgets, QtGui, uic

from Thread1 import *
from Thread2 import *

class QThreadsExample(QtWidgets.QMainWindow):
    def __init__(self):
        QtWidgets.QMainWindow.__init__(self)
        self.ui = uic.loadUi('QThreads_Example.ui',self)

        self.thread={}
        self.ui.pushButton_1.clicked.connect(self.start_thread_1)
        self.ui.pushButton_2.clicked.connect(self.stop_thread_1)
        
        self.ui.pushButton_3.clicked.connect(self.start_thread_2)
        self.ui.pushButton_4.clicked.connect(self.stop_thread_2)

    def start_thread_1(self):
        d = {
            "t1_value1": self.ui.lineEdit_t1_value1.text(),
            "t1_value2": self.ui.lineEdit_t1_value2.text(),
        }
        self.thread['Thread1'] = Thread1(parent=None, data=d)
        self.thread['Thread1'].start()
        self.thread['Thread1'].write_signal.connect(self.write)
        self.thread['Thread1'].finished_signal.connect(self.finished)

        self.ui.pushButton_1.setEnabled(False)
        self.ui.pushButton_2.setEnabled(True)
        
    def start_thread_2(self):
        d = {
            "t2_value1": self.ui.lineEdit_t2_value1.text(),
            "t2_value2": self.ui.lineEdit_t2_value2.text(),
            "t2_value3": self.ui.lineEdit_t2_value3.text(),
        }
        self.thread['Thread2'] = Thread2(parent=None, data=d)
        self.thread['Thread2'].start()
        self.thread['Thread2'].write_signal.connect(self.write)
        self.thread['Thread2'].finished_signal.connect(self.finished)

        self.ui.pushButton_3.setEnabled(False)
        self.ui.pushButton_4.setEnabled(True)
        
    def stop_thread_1(self):
        self.thread['Thread1'].stop()
        
    def stop_thread_2(self):
        self.thread['Thread2'].stop()

    def write(self, data):
        index = self.sender().__class__.__name__
        print(index + ': ' + data)
        if index == 'Thread1':
            current_text= self.ui.textBrowser_1.toPlainText()
            self.ui.textBrowser_1.setText(current_text + index + ': ' + data + '\n')
        if index == 'Thread2':
            current_text= self.ui.textBrowser_2.toPlainText()
            self.ui.textBrowser_2.setText(current_text + index + ': ' + data + '\n')

    def finished(self):
        index = self.sender().__class__.__name__
        if index == 'Thread1':
            self.write('finished')
            self.ui.pushButton_2.setEnabled(False)
            self.ui.pushButton_1.setEnabled(True)
        if index == 'Thread2':
            self.write('finished')
            self.ui.pushButton_4.setEnabled(False)
            self.ui.pushButton_3.setEnabled(True)

app = QtWidgets.QApplication(sys.argv)
mainWindow = QThreadsExample()
mainWindow.show()
sys.exit(app.exec_())
